#!/usr/bin/env bash

# Creates local-only credentials, a PostgreSQL database, a sample user, and a
# self-signed HTTPS certificate. It never writes a password to the terminal.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"

require_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "Missing required command: $1"
        echo "Install a JDK (17 or newer), Maven, PostgreSQL, and OpenSSL first."
        exit 1
    fi
}

for command in mvn psql createdb openssl; do
    require_command "$command"
done

JDK_HOME="$(mvn -version 2>&1 | awk -F 'runtime: ' '/runtime:/ {print $2; exit}')"
KEYTOOL="$JDK_HOME/bin/keytool"
if [[ ! -x "$KEYTOOL" ]]; then
    echo "Unable to find keytool for the JDK Maven is using."
    exit 1
fi

read_env_value() {
    grep -E "^$1=" .env 2>/dev/null | head -n 1 | cut -d= -f2- || true
}

if [[ -f .env ]]; then
    DB_PASSWORD="$(read_env_value DB_PASSWORD)"
    SSL_KEYSTORE_PASSWORD="$(read_env_value SSL_KEYSTORE_PASSWORD)"
    if [[ -z "$DB_PASSWORD" || -z "$SSL_KEYSTORE_PASSWORD" ]]; then
        echo ".env exists but is missing DB_PASSWORD or SSL_KEYSTORE_PASSWORD."
        exit 1
    fi
    echo "Using the existing local .env file."
else
    DB_PASSWORD="$(openssl rand -hex 24)"
    SSL_KEYSTORE_PASSWORD="$(openssl rand -hex 24)"
    umask 077
    cat > .env <<EOF
# Generated by scripts/setup-local.sh. This file is ignored by Git.
DB_URL=jdbc:postgresql://localhost:5432/secure_directory
DB_USERNAME=secure_directory_app
DB_PASSWORD=$DB_PASSWORD
SSL_KEYSTORE_PATH=file:$PROJECT_DIR/certs/secure-directory.p12
SSL_KEYSTORE_PASSWORD=$SSL_KEYSTORE_PASSWORD
SSL_KEY_ALIAS=secure-directory
HTTPS_PORT=8443
HTTP_PORT=8080
EOF
    chmod 600 .env
    echo "Created .env with local-only secrets."
fi

if [[ ! -f certs/secure-directory.p12 ]]; then
    mkdir -p certs
    "$KEYTOOL" -genkeypair \
        -alias secure-directory \
        -keyalg RSA \
        -keysize 3072 \
        -storetype PKCS12 \
        -keystore certs/secure-directory.p12 \
        -validity 365 \
        -storepass "$SSL_KEYSTORE_PASSWORD" \
        -dname "CN=localhost, OU=Development, O=MSCS-535, L=Local, ST=Local, C=US" \
        -ext "SAN=dns:localhost,ip:127.0.0.1"
    echo "Created a local HTTPS certificate."
fi

if ! psql --dbname=postgres --tuples-only --no-align --command "SELECT 1" >/dev/null 2>&1; then
    echo "PostgreSQL is not running or is not accepting local connections."
    echo "On macOS with Homebrew, run: brew services start postgresql"
    exit 1
fi

if ! psql --dbname=postgres --tuples-only --no-align \
    --command "SELECT 1 FROM pg_database WHERE datname = 'secure_directory'" | grep -qx "1"; then
    createdb secure_directory
    echo "Created secure_directory database."
fi

if ! psql --dbname=postgres --tuples-only --no-align \
    --command "SELECT 1 FROM pg_roles WHERE rolname = 'secure_directory_app'" | grep -qx "1"; then
    psql --dbname=postgres --set=app_db_password="$DB_PASSWORD" --file=database/01-create-role.sql
    echo "Created restricted application database role."
fi

if ! psql --dbname=secure_directory --tuples-only --no-align \
    --command "SELECT to_regclass('public.app_user')" | grep -qx "app_user"; then
    psql --dbname=secure_directory --file=database/02-schema.sql
    echo "Created application tables."
fi

if ! psql --dbname=secure_directory --tuples-only --no-align \
    --command "SELECT 1 FROM app_user WHERE username = 'student'" | grep -qx "1"; then
    read -r -s -p "Choose a password for the student account: " STUDENT_PASSWORD
    printf '\n'
    STUDENT_HASH="$(printf '%s\n' "$STUDENT_PASSWORD" | mvn -q -DskipTests compile \
        org.codehaus.mojo:exec-maven-plugin:3.5.0:java \
        -Dexec.mainClass=edu.mscs535.securedirectory.tools.PasswordHashGenerator)"
    unset STUDENT_PASSWORD
    if [[ ! "$STUDENT_HASH" =~ ^\$2[aby]\$[0-9]{2}\$ ]]; then
        echo "Could not generate a BCrypt password hash. Setup stopped."
        exit 1
    fi
    psql --dbname=secure_directory --set=bootstrap_password_hash="$STUDENT_HASH" \
        --file=database/03-sample-data.sql
    if ! psql --dbname=secure_directory --tuples-only --no-align \
        --command "SELECT 1 FROM app_user WHERE username = 'student' AND enabled" | grep -qx "1"; then
        echo "The student account was not created. Setup stopped."
        exit 1
    fi
    echo "Created the student account and sample employee data."
fi

echo
echo "Setup complete. Start the application with:"
echo "  mvn spring-boot:run"
