DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS app_user;

CREATE TABLE app_user (
    username VARCHAR(50) PRIMARY KEY,
    password_hash VARCHAR(60) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number VARCHAR(20) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    department VARCHAR(80) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE
);

INSERT INTO employee (employee_number, full_name, department, email) VALUES
    ('E-1001', 'Avery Morgan', 'Engineering', 'avery.morgan@example.test'),
    ('E-1002', 'Jordan Lee', 'Finance', 'jordan.lee@example.test');
